#!/bin/bash

# exit when any command fails
set -e
# keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
# echo an error message before exiting
trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT


echo "This script prepares the project to be run with docker. Dependences: maven, docker, node.";
echo;

echo "STEP1: Creating server's standalone jar and its Docker image";
(cd server;
 mvn package;
 docker build -t portacs-server .
)
echo;

echo "STEP2: Building Angular app and its Docker image";
(cd ui;
 npm install;
 ng build --prod;
 docker build -t portacs-ui .
)
echo;

echo "STEP3: Building unit and its Docker image";
(cd unit;
 npm install;
 tsc;
 docker build -t portacs-unit .
)
echo;

echo "STEP4: Building sensors and its Docker image";
(cd sensors;
 npm install;
 tsc;
 docker build -t portacs-sensors .
)
echo;

echo;
echo "Done.";
echo;
